project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  render:
    - '*.qmd' # Render all .qmd files in the root directory
    - '!exams/'
    - '!book/'

website:
  title: 'MATH316'
  navbar:
    tools:
      - icon: github
        href: https://github.com/nlunce/math316
    left:
      - href: ./homework/index.html
        text: HOMEWORK
      - href: ./exam-practice/index.html
        text: EXAM PRACTICE
      - href: ./notes/index.html
        text: NOTES
      - href: ./index.html
        text: SCHEDULE

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  warning: false
  message: false
