project:
  type: website
  preview:
    port: 3000
    browser: true
    watch-inputs: true
    navigate: true
  output-dir: docs
  render:
    - '*.qmd'
    - '!exams/'
    - '!book/'

website:
  title: 'MATH316'
  page-navigation: true
  navbar:
    tools:
      - icon: github
        href: https://github.com/nlunce/math316
    left:
      - href: ./homework/index.html
        text: HOMEWORK
      - href: ./exam-practice/index.html
        text: EXAM PRACTICE
      - href: ./notes/index.html
        text: NOTES
      - href: ./index.html
        text: SCHEDULE

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  warning: false
  message: false

preview:
  port: 3000
  serve: true
  browser: true
  watch-inputs: true
  navigate: true

jupyter: python3
