---
title: "FALL 2024 - SCHEDULE"
---


| Week | Monday                                                                          | Tuesday                                       | Wednesday                                     | Thursday                                                                                      | Friday                                                                                       |
| ---- | ------------------------------------------------------------------------------- | --------------------------------------------- | --------------------------------------------- | --------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| 1    | Introduction to Class                                                           | Systems of Equations (1.2)                    | Linear Combinations (1.3)                     | Span (1.4)                                                                                    | Linear Systems Revisited (1.5)                                                               |
| 2    | Linear Independence (1.6)                                                       | <span style="color:green">Homework Day</span> | Matrix Algebra                                | Inverse Matrices (1.7/1.8)                                                                    | Determinants (1.9)                                                                           |
| 3    | Vector Spaces (1.11)                                                            | Basis and Dimension (1.12)                    | <span style="color:green">Homework Day</span> | Integration Review - <span style="color:red">Exam #1 Open</span>                              | Integration Review - <span style="color:red">Exam #1 Closes</span>                           |
| 4    | Diff. Equations (2.2)                                                           | Initial Value Problems (2.2)                  | Linear First Order Equations (2.3)            | Applications (2.4)                                                                            | <span style="color:green">Homework Day</span>                                                |
| 5    | Nonlinear First Order Equations (2.5)                                           | Euler’s Method (2.6)                          | Applications (2.7)                            | <span style="color:green">Homework Day</span>                                                 | Complex Number Review - <span style="color:red">Exam #2 Open</span>                          |
| 6    | Homogeneous Equations (4.2/4.3) - <span style="color:red">Exam #2 Closes</span> | Nonhomogeneous Equations (4.4)                | Nonhomogeneous Equations (4.4)                | Applications - Forced Motion (4.5)                                                            | <span style="color:green">Homework Day</span> - <span style="color:red">Exam #3 Opens</span> |
| 7    | Eigenvalue Method (3.2-3.5)                                                     | <span style="color:red">Exam #3 Closes</span> | Eigenvalue Method (3.2–3.5)                   | Phase Portraits (3.2–3.5) - Exponential Matrix Method (3.9)                                   | <span style="color:green">Homework Day</span>                                                |
| 8    | Undetermined Coefficients (3.6)                                                 | Variation of Parameters (3.7)                 | Applications – Mixing Problem (3.8)           | Applications – Spring Mass, RLC Circuits (3.8)                                                | <span style="color:green">Homework Day</span> - <span style="color:red">Exam #4 Opens</span> |
| 9    | <span style="color:red">NO CLASS</span>                                         | <span style="color:red">Exam #4 Closes</span> | Inverse Laplace Transforms                    | IVP With Laplace Step Functions                                                               | Differential Equations with Laplace                                                          |
| 10   | <span style="color:green">Homework Day</span>                                   | <span style="color:red">NO CLASS</span>       | <span style="color:red">Exam #5 Opens</span>  | Differential Equations with Laplace                                                           | <span style="color:red">Exam #5 Closes</span> - Taylor Polynomials (8.2)                     |
| 11   | Power Series Solutions (8.3)                                                    | Power Series Solutions (8.3)                  | <span style="color:red">NO CLASS</span>       | <span style="color:red">NO CLASS</span>                                                       | <span style="color:red">NO CLASS</span>                                                      |
| 12   | <span style="color:green">Homework Day</span>                                   | Legendre’s Equation (8.4)                     | Review                                        | Legendre’s Equation (8.4)                                                                     | Hermite Equations (8.5)                                                                      |
| 13   | Method of Frobenius (8.6)                                                       | Laguerre Equations (8.5)                      | Bessel’s Equations (8.5)                      | <span style="color:green">Homework Day</span> - <span style="color:red">Exam #6 Review</span> | <span style="color:red">NO CLASS</span> - <span style="color:red">Exam #6 Opens</span>       |
| 14   | <span style="color:red">NO CLASS</span>                                         | <span style="color:red">NO CLASS</span>       | <span style="color:red">Exam #6 Closes</span> | Graduation Commencement & Convocations                                                        |                                                                                              |
